### ISSUE TITLE
Email no longer sent

### ISSUE THREAD

**Issue by naftalis** [hasadna/Open-Knesset#704]
The followers of agendas no longer receive daily or weekly emails with updates to the agenda. Last email was from June 24th.

**Comment by naftalis** [comment]
people who follow the agenda can choose whether they get daily digests or weekly with all the changes that happened in that period, or not at all. it's in their profile.
When I add a vote to he agenda I expect an email to be sent saying that "name of vote" was added to agenda. like so: 
ההצבעה להעביר את הצעת החוק לוועדה - הצעת חוק הצהרת הון של בעלי תפקידים בכירים בשירות המדינה וברשויות המקומיות, התשע"ה–2015 שויכה לאג'נדה. 
When I add a law proposal to the agenda I expect an email to be sent saying that "name of proposal" was added to agenda. like so: 
הצעת חוק שויכה לאג'נדה: חוק לימוד מורשת עדות ישראל חוק חדש
When I edit a ranking of a vote or law proposal I expect an email saying something like: 
שיוך הצעת חוק לאג'נדה עודכן: חוק כלי היריה תיקון - כניסה למטווחים




a sample email I would get would look like this:
עדכוני כנסת פתוחה

שלום naftalis,
הצעות חוק חמות באתר

לחצו על הקישורים הבאים כדי להצביע על הצעות חוק חמות באתר. חברי הכנסת מקבלים עדכונים שוטפים על עמדת המתפקדים, וכך אתם יכולים להשפיע על הצבעותיהם.

חוק שירותי רווחה לאנשים עם מוגבלות חוק חדש (עברה קריאה טרומית)
חוק גיל פרישה לאישה תיקוני חקיקה (הצעה)
חוק הגנה מפני שימוש במכשיר טלפון נייד והגבלת פרסומת חוק חדש (הצעה)

אג'נדות

אג'נדה מדד החופש לכנסת ה-20 בעריכת התנועה הליברלית החדשה

הצעת חוק שויכה לאג'נדה: חוק לימוד מורשת עדות ישראל חוק חדש 
הצעת חוק שויכה לאג'נדה: חוק זכויות הוריות תיקוני חקיקה 
הצעת חוק שויכה לאג'נדה: חוק לידה בבית תיקוני חקיקה 
ההצבעה להעביר את הצעת החוק לוועדה - הצעת חוק הצהרת הון של בעלי תפקידים בכירים בשירות המדינה וברשויות המקומיות, התשע"ה–2015 שויכה לאג'נדה. 
הצעת חוק שויכה לאג'נדה: חוק הצהרת הון של בעלי תפקידים בכירים בשירות המדינה וברשויות המקומיות חוק חדש 
ההצבעה להעביר את הצעת החוק לוועדה - הצעת חוק כלי היריה (תיקון – כניסה למטווחים), התשע"ה–2015 שויכה לאג'נדה. 
שיוך הצעת חוק לאג'נדה עודכן: חוק כלי היריה תיקון - כניסה למטווחים 
ההצבעה להעביר את הצעת החוק לוועדה - הצעת חוק כלי הירייה (תיקון - הגבלת גיל למתן רשיונות לכלי ירייה), התשע"ו-2016 שויכה לאג'נדה. 
הצעת חוק שויכה לאג'נדה: חוק כלי היריה תיקון - כניסה למטווחים 
הצעת חוק שויכה לאג'נדה: חוק כלי הירייה תיקון - הגבלת גיל למתן רשיונות לכלי ירייה 
ההצבעה להעביר את הצעת החוק לוועדה - הצעת חוק העונשין (תיקון – הסתה להשתמטות נגד מי שמתנדב לשירות בכוח מזוין), התשע"ה–2015 שויכה לאג'נדה. 
הצעת חוק שויכה לאג'נדה: חוק העונשין תיקון - הסתה להשתמטות נגד מי שמתנדב לשירות בכוח מזוין 
ההצבעה קריאה שנייה - הצעת חוק מיסוי מקרקעין (שבח ורכישה) (תיקון מס` 87), התשע"ו-2016 שויכה לאג'נדה. 
ההצבעה אישור החוק - הצעת חוק מיסוי מקרקעין (שבח ורכישה) (תיקון מס` 87), התשע"ו-2016 שויכה לאג'נדה. 
הח"כים התומכים ביותר באג'נדה

שרן השכל - ‎40
בצלאל סמוטריץ - ‎31
איוב קרא - ‎29
הח"כים המתנגדים ביותר לאג'נדה

יעל כהן פארן - ‎-41
איציק שמולי - ‎-43
מיקי לוי - ‎-47

על מנת להפסיק את קבלת העדכונים

יש לבקר באתר ולעדכן את הגדרות שליחת הדוא"ל

**Comment by alonisser** [comment]
Found evidence in cronlogs:
```
 1 09:02:08 ip-10-209-139-40 open_knesset: 2016-10-01 09:02:08,068#011root:101#011DEBUG#011released.
Oct  1 09:02:08 ip-10-209-139-40 open_knesset: Traceback (most recent call last):
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/Open-Knesset/manage.py", line 10, in <module>
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     execute_from_command_line(sys.argv)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 399, in execute_from_command_line
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     utility.execute()
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 392, in execute
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     self.fetch_command(subcommand).run_from_argv(self.argv)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/core/management/base.py", line 242, in run_from_argv
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     self.execute(*args, **options.__dict__)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/core/management/base.py", line 285, in execute
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     output = self.handle(*args, **options)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/src/django-mailer/mailer/management/commands/send_mail.py", line 26, in handle
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     send_all()
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/src/django-mailer/mailer/engine.py", line 149, in send_all
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     MessageLog.objects.log(message, RESULT_SUCCESS)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/src/django-mailer/mailer/models.py", line 262, in log
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     log_message=log_message,
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/manager.py", line 157, in create
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     return self.get_queryset().create(**kwargs)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/query.py", line 322, in create
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     obj.save(force_insert=True, using=self.db)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     force_update=force_update, update_fields=update_fields)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 654, in _save_table
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 687, in _do_insert
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     using=using, raw=raw)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/manager.py", line 232, in _insert
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     return insert_query(self.model, objs, fields, **kwargs)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/query.py", line 1514, in insert_query
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     return query.get_compiler(using=using).execute_sql(return_id)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 903, in execute_sql
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     cursor.execute(sql, params)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     return self.cursor.execute(sql, params)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     six.reraise(dj_exc_type, dj_exc_value, traceback)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:   File "/oknesset_data/oknesset/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:     return self.cursor.execute(sql, params)
Oct  1 09:02:08 ip-10-209-139-40 open_knesset: django.db.utils.ProgrammingError: column "message_id" of relation "mailer_messagelog" does not exist
Oct  1 09:02:08 ip-10-209-139-40 open_knesset: LINE 1: INSERT INTO "mailer_messagelog" ("message_data", "message_id...
Oct  1 09:02:08 ip-10-209-139-40 open_knesset:                                                          ^
Oct  1 09:02:08 ip-10-209-139-40 open_knesset: 
```

**Comment by alonisser** [comment]
requirements.txt
-e git://github.com/pinax/django-mailer.git#egg=django-mailer

Who thought that is a good idea? so we are bound to some cutting edge django mailer directly from github. which probably needs another version of django. wtf
