### ISSUE TITLE
שגיאה בהזנת קריא שלישית להצ"ח

### ISSUE THREAD

**Issue by maryLoi** [hasadna/Open-Knesset#799]
מנסה להזין קריאה שלישית ומקבלת שגיאה. משתחזר כל פעם. לא קורה אם אני מזינה הצבעה אחרת
[חוק חובת המכרזים תיקון - העדפה במכרזים לעסקים קטנים ובינוניים](https://www.oknesset.org/bill/9308/)

![image](https://cloud.githubusercontent.com/assets/8996235/21543777/18cb71cc-cdd2-11e6-8a5c-6193fe58bc7a.png)

------------------------------------------------------------------------------------------------------------------

עמוד שגיאה
![image](https://cloud.githubusercontent.com/assets/8996235/21543779/1b8361ae-cdd2-11e6-8bb6-16d940f17a5f.png)

**Comment by OriHoch** [comment]
I'm working on it

**Comment by OriHoch** [comment]
2017-01-11 17:30:45,169	django.request:224	ERROR	Internal Server Error: /bill/9308/
Traceback (most recent call last):
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_django.py", line 497, in wrapper
    return wrapped(*args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/oknesset_web/oknesset/Open-Knesset/laws/views.py", line 343, in dispatch
    return super(BillDetailView, self).dispatch(*args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/framework_django.py", line 835, in wrapper
    return wrapped(*args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 22, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/oknesset_web/oknesset/Open-Knesset/laws/views.py", line 450, in post
    bill.update_stage()
  File "/oknesset_web/oknesset/Open-Knesset/laws/models/bill.py", line 325, in update_stage
    self.save()
  File "/oknesset_web/oknesset/Open-Knesset/laws/models/bill.py", line 181, in save
    super(Bill, self).save(**kwargs)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 545, in save
    force_update=force_update, update_fields=update_fields)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 573, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 635, in _save_table
    forced_update)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/base.py", line 679, in _do_update
    return filtered._update(values) > 0
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/query.py", line 510, in _update
    return query.get_compiler(self.db).execute_sql(None)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 980, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 786, in execute_sql
    cursor.execute(sql, params)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/utils.py", line 99, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/db/backends/util.py", line 53, in execute
    return self.cursor.execute(sql, params)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 169, in execute
    return self._trace_sql(self.__wrapped__.execute, sql, params)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/opbeat/instrumentation/packages/dbapi2.py", line 179, in _trace_sql
    return method(sql, params)
  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/newrelic-2.40.0.34/newrelic/hooks/database_dbapi2.py", line 22, in execute
    *args, **kwargs)
IntegrityError: duplicate key value violates unique constraint "laws_bill_approval_vote_id_key"
DETAIL:  Key (approval_vote_id)=(10449) already exists.

**Comment by OriHoch** [comment]
the exception is from bill.update stage

```
/oknesset_data/oknesset/Open-Knesset/laws/models/bill.pyc in update_stage(self, force_update)
    323                 self.stage = BillStages.FAILED_APPROVAL
    324             self.stage_date = self.approval_vote.time.date()
--> 325             self.save()
    326             return
    327         for cm in self.second_committee_meetings.all():

/oknesset_data/oknesset/Open-Knesset/laws/models/bill.pyc in save(self, **kwargs)
    179         else:
    180             self.full_title = self.title
--> 181         super(Bill, self).save(**kwargs)
    182         for mk in self.proposers.all():
    183             mk.recalc_bill_statistics()
```

**Comment by OriHoch** [comment]
but it happens also when just manually setting approvel_vote and saving the bill

```
In [8]: bill
Out[8]: <Bill: חוק חובת המכרזים תיקון - העדפה במכרזים לעסקים קטנים ובינוניים (First Vote)>

In [9]: vote
Out[9]: <Vote: אישור החוק - הצעת חוק חובת המכרזים (תיקון מס` 25), התשע"ו-2016 (יום חמישי 04 אוגוסט 2016  02:18)>

In [10]: bill.approval_vote = vote
In [12]: bill.save()
---------------------------------------------------------------------------
IntegrityError                            Traceback (most recent call last)

```

**Comment by OriHoch** [comment]
@maryLoi  - 
The specific problem in this case is that the vote is already attached to another bill:
https://www.oknesset.org/bill/3003/

Currently we have a constraint that an approval vote must be attached to exactly one bill

If you delete this vote from the other bill you will be able to add it to this bill..

I opened a follow-up issue to make the error page more user friendly - #805
