### ISSUE TITLE
[Task] investigate error on production: AuthCanceled / facebook error

### ISSUE THREAD

**Issue by OriHoch** [hasadna/Open-Knesset#831]
```
Traceback (most recent call last):

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/apps/django_app/utils.py", line 52, in wrapper
    return func(request, backend, *args, **kwargs)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/apps/django_app/views.py", line 20, in complete
    redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/actions.py", line 43, in do_complete
    user = backend.complete(user=user, *args, **kwargs)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/backends/base.py", line 40, in complete
    return self.auth_complete(*args, **kwargs)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/backends/facebook.py", line 59, in auth_complete
    self.process_error(self.data)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/backends/facebook.py", line 52, in process_error
    super(FacebookOAuth2, self).process_error(data)

  File "/oknesset_web/oknesset/local/lib/python2.7/site-packages/social/backends/oauth.py", line 349, in process_error
    raise AuthCanceled(self, data.get('error_description', ''))

AuthCanceled: Authentication process canceled
```

**Comment by alonisser** [comment]
@OriHoch This is only about exception handling, recreation I believe is quite easy, If I'm not mistaken, someone starts facebook auth and does not authorize

**Comment by alonisser** [comment]
Nothing to do with devops etc
